#!/bin/sh
if [ "$2" == "merge" ]; then
  GIT_HEAD=$(env | grep GITHEAD)
  SOURCE_BRANCH_NAME="${GIT_HEAD##*=}"
  TARGET_BRANCH_NAME=$(git symbolic-ref --short HEAD)
  echo "Merge branch '$SOURCE_BRANCH_NAME' into '$TARGET_BRANCH_NAME'" > $1
fi
